export const surpriseMePrompts = [
  'uma poltrona em forma de abacate',
  'uma pintura a óleo surrealista onírica de Salvador Dalí de um gato jogando damas',
  'ursinhos de pelúcia comprando mantimentos no Japão, ukiyo-e',
  'uma pintura a óleo de Matisse de um robô humanóide jogando xadrez',
  'panda cientista louco misturando produtos químicos brilhantes, arte digital',
  'uma fotografia macro de 35 mm de dois ratos no Havaí, cada um deles vestindo minúsculos maiôs e carregando pequenas pranchas de surfe, arte digital',
  'Renderização 3D de um peixe tropical bonito em um aquário em um fundo azul escuro, arte digital',
  'um astronauta descansando em um resort tropical no espaço, vaporwave',
  'um retrato de pintura a óleo de uma capivara vestindo vestes reais medievais e uma coroa ornamentada em um fundo escuro',
  'um vitral representando um hambúrguer e batatas fritas',
  'um desenho a lápis e aquarela de uma cidade brilhante no futuro com carros voadores',
  'um lounge interno iluminado pelo sol com uma piscina de água transparente e outra piscina com água rosa pastel translúcida, ao lado de uma grande janela, arte digital',
  'um shiba inu adivinhador lendo seu destino em um hambúrguer gigante, arte digital',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
];
